// How strongly each preset's equations listen for a beat: bass attack, then the rest of
// the low end. The quiet third, the middle third, and the loud third. organic12 has no
// source file in the pack, so it sits in the middle.

export type Scene = 'soft' | 'pulse' | 'hard'

export const SOFT_PRESETS = [
  'Flexi - alien fish pond',
  '_Geiss - Artifact 01',
  'Geiss, Flexi + Stahlregen - Thumbdrum Tokamak [crossfiring aftermath jelly mashup]',
  'Aderrasi + Geiss - Airhandler (Kali Mix) - Canvas Mix',
  'Geiss - Cauldron - painterly 2 (saturation remix)',
  'cope + martin - mother-of-pearl',
  'Flexi - area 51',
  'Geiss - Thumb Drum',
  'flexi - what is the matrix',
  'flexi - patternton, district of media, capitol of the united abstractions of fractopia',
  'martin - mandelbox explorer - high speed demo version',
  'AdamFx 2 Geiss, Zylot and Flexi - Reaction Diffusion 3 (Overload Mix 2) EATIT4 hypno',
  'Eo.S. + Zylot - skylight (Stained Glass Majesty mix)',
  'martin - stormy sea (2010 update)',
  'martin - The Bridge of Khazad-Dum',
  'Flexi + stahlregen - jelly showoff parade',
  'martin - frosty caves 2',
  'Fumbling_Foo + En D & Martin - Mandelverse',
  'Flexi - truly soft piece of software - this is generic texturing (Jelly) ',
  'suksma - uninitialized variabowl (hydroponic chronic)',
  'martin - extreme heat',
  'martin - angel flight',
  'Martin - liquid arrows',
  '_Mig_085',
  'Flexi, martin + geiss - dedicated to the sherwin maxawow',
  'Flexi - smashing fractals [acid etching mix]',
  'Flexi - mindblob [shiny mix]',
  'flexi - swing out on the spiral',
  'Flexi + Martin - cascading decay swing',
  'Flexi + amandio c - piercing 05 - Kopie (2) - Kopie',
  'Flexi - infused with the spiral',
  'ORB - Waaa',
  'Flexi - mindblob mix',
  'cope + flexi - colorful marble (ghost mix)',
  'flexi + geiss - pogo cubes vs. tokamak vs. game of life [stahls jelly 4.5 finish]',
] as const

export const PULSE_PRESETS = [
  'flexi - bouncing balls [double mindblob neon mix]',
  'flexi - mom, why the sky looks different today',
  'Zylot - Paint Spill (Music Reactive Paint Mix)',
  'shifter - dark tides bdrv mix 2',
  'Aderrasi - Potion of Spirits',
  "TonyMilkdrop - Magellan's Nebula [Flexi - you enter first + multiverse]",
  'Rovastar - Oozing Resistance',
  '_Geiss - Desert Rose 2',
  'Geiss - Spiral Artifact',
  'Martin - acid wiring',
  'martin - another kind of groove',
  'martin - castle in the air',
  'Martin - charisma',
  'martin - mucus cervix',
  'martin - reflections on black tiles',
  'flexi + amandio c - organic [random mashup]',
  'An AdamFX n Martin Infusion 2 flexi - Why The Sky Looks Diffrent Today - AdamFx n Martin Infusion - Tack Tile Disfunction B',
  "TonyMilkdrop - Leonardo Da Vinci's Balloon [Flexi - merry-go-round + techstyle]",
  'Unchained - Unified Drag 2',
  'martin - bombyx mori',
  'martin - disco mix 4',
  'shifter - escape (sigur ros)',
  '_Aderrasi - Wanderer in Curved Space - mash0000 - faclempt kibitzing meshuggana schmaltz (Geiss color mix)',
  'yin - 393 - Artificial Inspiration (music driven - outward)',
  'Phat+fiShbRaiN+Eo.S_Mandala_Chasers_remix',
  'yin - 191 - Temporal singularities',
  'high-altitude basket unraveling - singh grooves nitrogen argon nz+',
  '_Rovastar + Geiss - Hurricane Nightmare (Posterize Mix)',
  'Cope - The Neverending Explosion of Red Liquid Fire',
  'Geiss + Flexi + Martin - disconnected',
  'Flexi + Martin - astral projection',
  'Rovastar + Loadus + Geiss - FractalDrop (Triple Mix)',
  'suksma - vector exp 1 - couldn′t not',
  'Halfbreak - Light of Breakers',
  'martin - chain breaker',
  'flexi + amandio c - organic12-3d-2.milk',
] as const

export const HARD_PRESETS = [
  'martin - witchcraft reloaded',
  'Unchained - Rewop',
  'Zylot - True Visionary (Final Mix)',
  'suksma - heretical crosscut playpen',
  'martin, flexi, fishbrain + sto - enterstate [random mashup]',
  'Geiss - Reaction Diffusion 2',
  'Flexi, fishbrain, Geiss + Martin - tokamak witchery',
  '$$$ Royal - Mashup (431)',
  'martin - fruit machine',
  'Aderrasi - Storm of the Eye (Thunder) - mash0000 - quasi pseudo meta concentrics',
  'fiShbRaiN + Flexi - witchcraft 2.0',
  'suksma - ed geining hateops - squeakers',
  '_Mig_049',
  'Zylot - Star Ornament',
  'Milk Artist At our Best - FED - SlowFast Ft AdamFX n Martin - HD CosmoFX',
  '_Geiss - untitled',
  'martin - glass corridor',
  'MilkDrop2077.R033',
  'suksma - Rovastar - Sunflower Passion (Enlightment Mix)_Phat_edit + flexi und martin shaders - circumflex in character classes in regular expression',
  'martin [shadow harlequins shape code] - fata morgana',
  'Goody - The Wild Vort',
  'Eo.S. - glowsticks v2 05 and proton lights (+Krash′s beat code) _Phat_remix02b',
  'shifter - liquid circuitry - conjugoth',
  'Hexcollie, Pieturp, Orb, Flexi, Geiss n Demon Lord - Premeditative Urination Clause',
  'flexi + fishbrain - neon mindblob grafitti',
  'MilkDrop2077.R002',
  '$$$ Royal - Mashup (197)',
  'Flexi - predator-prey-spirals',
  'LuxXx - Play v3 (the war within all of us)',
  'Halfbreak - Funny Madness',
  'sawtooth grin roam',
  '$$$ Royal - Mashup (220)',
  'martin + flexi - diamond cutter [prismaticvortex.com] - camille - i wish i wish i wish i was constrained',
  'gunthry is out back bloodying up the pine trees - adm atomising (v) the disintigrate (n)',
  'suksma - Hexcollie - Julian Carnival - shimmy dumb grid',
  'ShadowHarlequin - LovelyShinySquares [ liquid starburst rmx ] - unchained + rovaster - luckless - martin - starfield sector',
] as const
