import type { ColorToken } from './tokens'

/* The themes that ship with the app, written out the same way a person's own theme would be.
   Adding another is adding an object to the array below and nothing else.

   `musimo-dark` must stay equal to the `@theme` block in `src/style.css`, because that block is
   what paints the app when no theme is applied. `themes.test.ts` parses the sheet and compares the
   two, so the pair cannot drift.

   Every other built-in pairs a dark and a light scheme under one family name. `good`, `warn`,
   `danger`, `partial` and the media/scrim/shadow tokens are the same hex across every family (taken
   from `musimo-dark` for the dark half and from the light e2e fixture, `Paper`, for the light half),
   so an error is always the same red and a warning always the same amber no matter which theme is
   active. Windows 95 is the one family that breaks that rule on purpose, since matching the real
   Windows 95 palette is the point of it. */

/** Sets `color-scheme`, so native dialogs, scrollbars and form controls follow the theme. */
export type ColorScheme = 'dark' | 'light'

export type Theme = {
  /** `musimo-dark` for the built-in, `custom-<uuid>` for a person's own. */
  id: string
  name: string
  scheme: ColorScheme
  colors: Record<ColorToken, string>
}

export const DEFAULT_THEME_ID = 'musimo-dark'

export const BUILT_IN_THEMES = [
  {
    id: DEFAULT_THEME_ID,
    name: 'Musimo dark',
    scheme: 'dark',
    colors: {
      '--color-canvas': '#111716',
      '--color-sidebar': '#0e1312',
      '--color-raised': '#17201b',
      '--color-sunken': '#151c19',
      '--color-hover': '#1e2a23',
      '--color-active': '#263327',
      '--color-media': '#020305',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#e8ece8',
      '--color-muted': '#93a39b',
      '--color-faint': '#819088',
      '--color-line': '#2a3630',
      '--color-line-strong': '#344035',
      '--color-accent': '#c3e4a2',
      '--color-accent-ink': '#172014',
      '--color-accent-hot': '#d9ff73',
      '--color-good': '#c3e4a2',
      '--color-good-bg': '#283a28',
      '--color-good-line': '#4b6743',
      '--color-warn': '#f8ca76',
      '--color-warn-bg': '#342e1d',
      '--color-danger': '#efbaa2',
      '--color-danger-bg': '#39251f',
      '--color-danger-line': '#674343',
      '--color-owned-bg': '#2a3a27',
      '--color-partial': '#e4cc9c',
      '--color-partial-bg': '#3a3224',
      '--color-partial-line': '#4b4b3a',
    },
  },
  {
    id: 'musimo-light',
    name: 'Musimo light',
    scheme: 'light',
    colors: {
      '--color-canvas': '#f4f6f3',
      '--color-sidebar': '#e7ece4',
      '--color-raised': '#ffffff',
      '--color-sunken': '#ecf0ea',
      '--color-hover': '#dbe5d7',
      '--color-active': '#cadbc2',
      '--color-media': '#0b0d0a',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#1c2518',
      '--color-muted': '#4c5946',
      '--color-faint': '#596553',
      '--color-line': '#c8d7c1',
      '--color-line-strong': '#a5bd98',
      '--color-accent': '#375b25',
      '--color-accent-ink': '#ffffff',
      '--color-accent-hot': '#2e551b',
      '--color-good': '#2e5c22',
      '--color-good-bg': '#dfeed6',
      '--color-good-line': '#7d9b71',
      '--color-warn': '#6d4a06',
      '--color-warn-bg': '#f6ecd6',
      '--color-danger': '#8a2b16',
      '--color-danger-bg': '#f8e3dc',
      '--color-danger-line': '#bd8875',
      '--color-owned-bg': '#dcead2',
      '--color-partial': '#6b5109',
      '--color-partial-bg': '#f3ecd8',
      '--color-partial-line': '#c3b78c',
    },
  },
  {
    id: 'slate-dark',
    name: 'Slate dark',
    scheme: 'dark',
    colors: {
      '--color-canvas': '#121417',
      '--color-sidebar': '#0d0f12',
      '--color-raised': '#1a1f23',
      '--color-sunken': '#161a1d',
      '--color-hover': '#212930',
      '--color-active': '#29333d',
      '--color-media': '#020305',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#e8ebed',
      '--color-muted': '#9da6af',
      '--color-faint': '#89919a',
      '--color-line': '#29333d',
      '--color-line-strong': '#354250',
      '--color-accent': '#8bb8e4',
      '--color-accent-ink': '#141a1f',
      '--color-accent-hot': '#a5ccf3',
      '--color-good': '#c3e4a2',
      '--color-good-bg': '#283a28',
      '--color-good-line': '#4b6743',
      '--color-warn': '#f8ca76',
      '--color-warn-bg': '#342e1d',
      '--color-danger': '#efbaa2',
      '--color-danger-bg': '#39251f',
      '--color-danger-line': '#674343',
      '--color-owned-bg': '#2a3a27',
      '--color-partial': '#e4cc9c',
      '--color-partial-bg': '#3a3224',
      '--color-partial-line': '#4b4b3a',
    },
  },
  {
    id: 'slate-light',
    name: 'Slate light',
    scheme: 'light',
    colors: {
      '--color-canvas': '#f3f5f7',
      '--color-sidebar': '#e3e8ed',
      '--color-raised': '#ffffff',
      '--color-sunken': '#eaedf1',
      '--color-hover': '#d6dee6',
      '--color-active': '#c1cfdc',
      '--color-media': '#0b0d0a',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#181f25',
      '--color-muted': '#464f59',
      '--color-faint': '#535c65',
      '--color-line': '#c0ccd8',
      '--color-line-strong': '#97abbf',
      '--color-accent': '#275486',
      '--color-accent-ink': '#ffffff',
      '--color-accent-hot': '#194476',
      '--color-good': '#2e5c22',
      '--color-good-bg': '#dfeed6',
      '--color-good-line': '#7d9b71',
      '--color-warn': '#6d4a06',
      '--color-warn-bg': '#f6ecd6',
      '--color-danger': '#8a2b16',
      '--color-danger-bg': '#f8e3dc',
      '--color-danger-line': '#bd8875',
      '--color-owned-bg': '#dcead2',
      '--color-partial': '#6b5109',
      '--color-partial-bg': '#f3ecd8',
      '--color-partial-line': '#c3b78c',
    },
  },
  {
    id: 'sunset-dark',
    name: 'Sunset dark',
    scheme: 'dark',
    colors: {
      '--color-canvas': '#181411',
      '--color-sidebar': '#120f0d',
      '--color-raised': '#241d19',
      '--color-sunken': '#1e1815',
      '--color-hover': '#312721',
      '--color-active': '#3e3028',
      '--color-media': '#020305',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#edeae8',
      '--color-muted': '#afa39d',
      '--color-faint': '#9a8f89',
      '--color-line': '#3e3028',
      '--color-line-strong': '#513e34',
      '--color-accent': '#eca465',
      '--color-accent-ink': '#1f1914',
      '--color-accent-hot': '#fab97f',
      '--color-good': '#c3e4a2',
      '--color-good-bg': '#283a28',
      '--color-good-line': '#4b6743',
      '--color-warn': '#f8ca76',
      '--color-warn-bg': '#342e1d',
      '--color-danger': '#efbaa2',
      '--color-danger-bg': '#39251f',
      '--color-danger-line': '#674343',
      '--color-owned-bg': '#2a3a27',
      '--color-partial': '#e4cc9c',
      '--color-partial-bg': '#3a3224',
      '--color-partial-line': '#4b4b3a',
    },
  },
  {
    id: 'sunset-light',
    name: 'Sunset light',
    scheme: 'light',
    colors: {
      '--color-canvas': '#f7f4f2',
      '--color-sidebar': '#eee7e2',
      '--color-raised': '#ffffff',
      '--color-sunken': '#f2ece9',
      '--color-hover': '#e8dcd4',
      '--color-active': '#dfcbbe',
      '--color-media': '#0b0d0a',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#251d18',
      '--color-muted': '#594d46',
      '--color-faint': '#655a53',
      '--color-line': '#dbc9bd',
      '--color-line-strong': '#c4a692',
      '--color-accent': '#ad5a1a',
      '--color-accent-ink': '#ffffff',
      '--color-accent-hot': '#9b4b0d',
      '--color-good': '#2e5c22',
      '--color-good-bg': '#dfeed6',
      '--color-good-line': '#7d9b71',
      '--color-warn': '#6d4a06',
      '--color-warn-bg': '#f6ecd6',
      '--color-danger': '#8a2b16',
      '--color-danger-bg': '#f8e3dc',
      '--color-danger-line': '#bd8875',
      '--color-owned-bg': '#dcead2',
      '--color-partial': '#6b5109',
      '--color-partial-bg': '#f3ecd8',
      '--color-partial-line': '#c3b78c',
    },
  },
  {
    id: 'violet-dark',
    name: 'Violet dark',
    scheme: 'dark',
    colors: {
      '--color-canvas': '#141118',
      '--color-sidebar': '#0f0d12',
      '--color-raised': '#1d1924',
      '--color-sunken': '#18151e',
      '--color-hover': '#272131',
      '--color-active': '#30283e',
      '--color-media': '#020305',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#eae8ed',
      '--color-muted': '#a39daf',
      '--color-faint': '#8f899a',
      '--color-line': '#30283e',
      '--color-line-strong': '#3e3451',
      '--color-accent': '#b79aea',
      '--color-accent-ink': '#18141f',
      '--color-accent-hot': '#c7acf6',
      '--color-good': '#c3e4a2',
      '--color-good-bg': '#283a28',
      '--color-good-line': '#4b6743',
      '--color-warn': '#f8ca76',
      '--color-warn-bg': '#342e1d',
      '--color-danger': '#efbaa2',
      '--color-danger-bg': '#39251f',
      '--color-danger-line': '#674343',
      '--color-owned-bg': '#2a3a27',
      '--color-partial': '#e4cc9c',
      '--color-partial-bg': '#3a3224',
      '--color-partial-line': '#4b4b3a',
    },
  },
  {
    id: 'violet-light',
    name: 'Violet light',
    scheme: 'light',
    colors: {
      '--color-canvas': '#f4f3f7',
      '--color-sidebar': '#e7e3ee',
      '--color-raised': '#ffffff',
      '--color-sunken': '#ece9f1',
      '--color-hover': '#dcd5e7',
      '--color-active': '#cbbfde',
      '--color-media': '#0b0d0a',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#1d1825',
      '--color-muted': '#4d4659',
      '--color-faint': '#5a5365',
      '--color-line': '#c9beda',
      '--color-line-strong': '#a693c2',
      '--color-accent': '#653e98',
      '--color-accent-ink': '#ffffff',
      '--color-accent-hot': '#4e2880',
      '--color-good': '#2e5c22',
      '--color-good-bg': '#dfeed6',
      '--color-good-line': '#7d9b71',
      '--color-warn': '#6d4a06',
      '--color-warn-bg': '#f6ecd6',
      '--color-danger': '#8a2b16',
      '--color-danger-bg': '#f8e3dc',
      '--color-danger-line': '#bd8875',
      '--color-owned-bg': '#dcead2',
      '--color-partial': '#6b5109',
      '--color-partial-bg': '#f3ecd8',
      '--color-partial-line': '#c3b78c',
    },
  },
  {
    id: 'graphite-dark',
    name: 'Graphite dark',
    scheme: 'dark',
    colors: {
      '--color-canvas': '#141515',
      '--color-sidebar': '#0f1010',
      '--color-raised': '#1d1f20',
      '--color-sunken': '#191a1a',
      '--color-hover': '#262a2c',
      '--color-active': '#2e3538',
      '--color-media': '#020305',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#e8eced',
      '--color-muted': '#9da9af',
      '--color-faint': '#89949a',
      '--color-line': '#2e3538',
      '--color-line-strong': '#3c4448',
      '--color-accent': '#90cbdf',
      '--color-accent-ink': '#141c1f',
      '--color-accent-hot': '#a8def0',
      '--color-good': '#c3e4a2',
      '--color-good-bg': '#283a28',
      '--color-good-line': '#4b6743',
      '--color-warn': '#f8ca76',
      '--color-warn-bg': '#342e1d',
      '--color-danger': '#efbaa2',
      '--color-danger-bg': '#39251f',
      '--color-danger-line': '#674343',
      '--color-owned-bg': '#2a3a27',
      '--color-partial': '#e4cc9c',
      '--color-partial-bg': '#3a3224',
      '--color-partial-line': '#4b4b3a',
    },
  },
  {
    id: 'graphite-light',
    name: 'Graphite light',
    scheme: 'light',
    colors: {
      '--color-canvas': '#f4f5f5',
      '--color-sidebar': '#e6e9ea',
      '--color-raised': '#ffffff',
      '--color-sunken': '#eceeee',
      '--color-hover': '#dadfe1',
      '--color-active': '#c7d1d6',
      '--color-media': '#0b0d0a',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#182125',
      '--color-muted': '#465259',
      '--color-faint': '#535f65',
      '--color-line': '#c6ced2',
      '--color-line-strong': '#a2aeb4',
      '--color-accent': '#176582',
      '--color-accent-ink': '#ffffff',
      '--color-accent-hot': '#0c546e',
      '--color-good': '#2e5c22',
      '--color-good-bg': '#dfeed6',
      '--color-good-line': '#7d9b71',
      '--color-warn': '#6d4a06',
      '--color-warn-bg': '#f6ecd6',
      '--color-danger': '#8a2b16',
      '--color-danger-bg': '#f8e3dc',
      '--color-danger-line': '#bd8875',
      '--color-owned-bg': '#dcead2',
      '--color-partial': '#6b5109',
      '--color-partial-bg': '#f3ecd8',
      '--color-partial-line': '#c3b78c',
    },
  },
  {
    id: 'win95-dark',
    name: 'Windows 95 dark',
    scheme: 'dark',
    colors: {
      '--color-canvas': '#000000',
      '--color-sidebar': '#000000',
      '--color-raised': '#0c0c0c',
      '--color-sunken': '#000000',
      '--color-hover': '#1a1a1a',
      '--color-active': '#264a7a',
      '--color-media': '#000000',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#ffffff',
      '--color-muted': '#c0c0c0',
      '--color-faint': '#a6a6a6',
      '--color-line': '#4d4d4d',
      '--color-line-strong': '#808080',
      '--color-accent': '#3fa9f5',
      '--color-accent-ink': '#001233',
      '--color-accent-hot': '#ffe066',
      '--color-good': '#4fd15e',
      '--color-good-bg': '#0f2a12',
      '--color-good-line': '#2e6b35',
      '--color-warn': '#ffe066',
      '--color-warn-bg': '#332b06',
      '--color-danger': '#ff6b6b',
      '--color-danger-bg': '#3a0f0f',
      '--color-danger-line': '#7a2e2e',
      '--color-owned-bg': '#0f2a12',
      '--color-partial': '#ffe066',
      '--color-partial-bg': '#332b06',
      '--color-partial-line': '#665711',
    },
  },
  {
    id: 'win95-light',
    name: 'Windows 95 light',
    scheme: 'light',
    colors: {
      '--color-canvas': '#c0c0c0',
      '--color-sidebar': '#008080',
      '--color-raised': '#ffffff',
      '--color-sunken': '#dfdfdf',
      '--color-hover': '#d4d0c8',
      '--color-active': '#aac4e0',
      '--color-media': '#000000',
      '--color-on-media': '#ffffff',
      '--color-scrim': '#000000',
      '--color-shadow': '#000000',
      '--color-text': '#000000',
      '--color-muted': '#404040',
      '--color-faint': '#4d4d4d',
      '--color-line': '#808080',
      '--color-line-strong': '#404040',
      '--color-accent': '#000080',
      '--color-accent-ink': '#ffffff',
      '--color-accent-hot': '#1084d0',
      '--color-good': '#006400',
      '--color-good-bg': '#c8e6c9',
      '--color-good-line': '#4b8b4b',
      '--color-warn': '#7a5b00',
      '--color-warn-bg': '#fff3b0',
      '--color-danger': '#aa0000',
      '--color-danger-bg': '#ffd6d6',
      '--color-danger-line': '#c47f7f',
      '--color-owned-bg': '#c8e6c9',
      '--color-partial': '#7a5b00',
      '--color-partial-bg': '#fff3b0',
      '--color-partial-line': '#c9b877',
    },
  },
] as const satisfies readonly Theme[]

export const DEFAULT_THEME: Theme = BUILT_IN_THEMES[0]
